# Generated by Django 2.0 on 2019-03-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_auto_20190304_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('MovieId', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
