# Generated by Django 2.0 on 2019-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_auto_20190305_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovieID',
            field=models.CharField(max_length=50),
        ),
    ]
