# Generated by Django 2.0 on 2019-03-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_auto_20190305_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='MovieID',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
