# Generated by Django 2.1.7 on 2019-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0008_movie_movieid'),
    ]

    operations = [
        migrations.CreateModel(
            name='watched_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('MovieTitle', models.CharField(max_length=111)),
            ],
        ),
    ]
