# Generated by Django 2.1.7 on 2019-03-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0009_watched_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='MovieId',
            new_name='MovieID',
        ),
    ]
