# Generated by Django 2.0 on 2019-03-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20190304_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
