# Generated by Django 2.0 on 2019-03-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20190304_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
